name: Build,Package on Manual Trigger

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true

jobs:
  win-build-and-package:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.27.1'
      - name: get dependencies
        run: flutter pub get
      - name: enable windows build
        run: flutter config --enable-windows-desktop
      - name: build
        run: flutter build windows --release
      - name: Zip release
        uses: TheDoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: SDImageViewer-${{github.event.inputs.tag}}-windows.zip
          directory: build/windows/x64/runner/Release
      - name: Window release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: build/windows/x64/runner/Release/SDImageViewer-${{github.event.inputs.tag}}-windows.zip
          generateReleaseNotes: false
          tag: ${{ github.event.inputs.tag }}
          token: ${{ secrets.REPO_TOKEN }}
